# Generated by Django 4.2.4 on 2023-08-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.CharField(blank=True, max_length=100)),
                ('Image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
